version: "3.4"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      target: server      
    ports:
      - "8080:8080"
    environment:
      - USE_LOCAL_SOURCE=true
    volumes:
      - ./cache:/var/cache/cantaloupe
    restart: always
